In [2]:
from PIL import Image
import numpy as np
from skimage import transform
import os
import shutil
import tensorflow as tf
from tensorflow import keras
import cv2
import time


def load(image):
      
    np_image = np.array(image).astype('float32')/255
    np_image = transform.resize(np_image, (128,128,3))
    np_image = np.expand_dims(np_image, axis=0)
    return np_image

def predict_result(image,threshold):
    outputs = model.predict(image)  
    
    s = outputs[0][0]
    if s >= threshold:  
        status = 1     
    else:
        status = 0
    return s, status

In [8]:
def load(image):
      
    np_image = np.array(image).astype('float32')/255
    np_image = transform.resize(np_image, (128,128,3))
   
    np_image2 = np.expand_dims(np_image, axis=0)
   
    return np_image, np_image2

raw = cv2.imread(r"D:\Dementia_Data_Preprocessing\testing_data\20211027\all\20211027_t000003.jpg",0)    
a = load(raw)[0]
b = load(raw)[1]
print(a)



[[[0.4045343  0.4045343  0.4045343 ]
  [0.4060049  0.4060049  0.4060049 ]
  [0.4060049  0.4060049  0.4060049 ]
  ...
  [0.3954657  0.3954657  0.3954657 ]
  [0.3954657  0.3954657  0.3954657 ]
  [0.3959559  0.3959559  0.3959559 ]]

 [[0.40968138 0.40968138 0.40968138]
  [0.41409314 0.41409314 0.41409314]
  [0.41409314 0.41409314 0.41409314]
  ...
  [0.39914218 0.39914218 0.39914218]
  [0.39914218 0.39914218 0.39914218]
  [0.40257353 0.40257353 0.40257353]]

 [[0.41482845 0.41482845 0.41482845]
  [0.42218137 0.42218137 0.42218137]
  [0.42218137 0.42218137 0.42218137]
  ...
  [0.40281862 0.40281862 0.40281862]
  [0.40281862 0.40281862 0.40281862]
  [0.4091912  0.4091912  0.4091912 ]]

 ...

 [[0.37823224 0.37823224 0.37823224]
  [0.37428004 0.37428004 0.37428004]
  [0.37428004 0.37428004 0.37428004]
  ...
  [0.40078124 0.40078124 0.40078124]
  [0.40078124 0.40078124 0.40078124]
  [0.3971967  0.3971967  0.3971967 ]]

 [[0.37703738 0.37703738 0.37703738]
  [0.37290135 0.37290135 0.37290135]


In [9]:
print(b)

[[[[0.4045343  0.4045343  0.4045343 ]
   [0.4060049  0.4060049  0.4060049 ]
   [0.4060049  0.4060049  0.4060049 ]
   ...
   [0.3954657  0.3954657  0.3954657 ]
   [0.3954657  0.3954657  0.3954657 ]
   [0.3959559  0.3959559  0.3959559 ]]

  [[0.40968138 0.40968138 0.40968138]
   [0.41409314 0.41409314 0.41409314]
   [0.41409314 0.41409314 0.41409314]
   ...
   [0.39914218 0.39914218 0.39914218]
   [0.39914218 0.39914218 0.39914218]
   [0.40257353 0.40257353 0.40257353]]

  [[0.41482845 0.41482845 0.41482845]
   [0.42218137 0.42218137 0.42218137]
   [0.42218137 0.42218137 0.42218137]
   ...
   [0.40281862 0.40281862 0.40281862]
   [0.40281862 0.40281862 0.40281862]
   [0.4091912  0.4091912  0.4091912 ]]

  ...

  [[0.37823224 0.37823224 0.37823224]
   [0.37428004 0.37428004 0.37428004]
   [0.37428004 0.37428004 0.37428004]
   ...
   [0.40078124 0.40078124 0.40078124]
   [0.40078124 0.40078124 0.40078124]
   [0.3971967  0.3971967  0.3971967 ]]

  [[0.37703738 0.37703738 0.37703738]
   [0.3

In [2]:
def get_two_area_stdev(gray_image):

    
    cropped = gray_image[0:16, 0:32]
    crop2 = gray_image[16:24, 0:32]

    arr = np.array(cropped)
    arr2 = arr.flatten()

    arr_b = np.array(crop2)
    arr_b2 = arr_b.flatten()

    a = np.std(arr2, ddof=1)
    b = np.std(arr_b2, ddof=1)

    return a,b

In [3]:
def magic_eraser(img, threshold):
    img_copy = img
    shape = img.shape
    ymax = shape[0]
    xmax = shape[1]
    for i in range(ymax):   
        for j in range(xmax):
            count = 0
            adjacent_list = []  

            now_pixel = int(img[i][j])

            if j-1 >= 0:
                count+=1
                up_pixel = int(img[i][j-1])

                if abs(up_pixel - now_pixel) > threshold:               
                    adjacent_list.append(up_pixel)            

            if j+1 < xmax:
                count+=1
                down_pixel = int(img[i][j+1])

                if abs(down_pixel - now_pixel) > threshold:               
                    adjacent_list.append(down_pixel)   

            if i-1 >= 0:
                count+=1
                left_pixel = int(img[i-1][j])

                if abs(left_pixel - now_pixel) > threshold:               
                    adjacent_list.append(left_pixel) 

            if i+1 < ymax:
                count+=1
                right_pixel = int(img[i+1][j])

                if abs(right_pixel - now_pixel) > threshold:  
                    adjacent_list.append(right_pixel)

            if count == len(adjacent_list):

                average = int(sum(adjacent_list)/count)          
                img_copy[i][j] = average 
        
    return img_copy

In [4]:
def list_to_stack(list_a, restrict):
    if len(list_a)>restrict:
        list_a.pop(0)   

In [5]:
def calculate_slope(x1,y1,x2,y2):
    x = (y2 - y1) / (x2 - x1)
    return x

In [6]:
def heat_remain_algorithm(b):
    slope = calculate_slope(0,b[0],1,b[2])
    print("slope:",slope)
    if slope <= -3:
        return "leave bed"
    else:
        return "still on bed"

In [7]:
def heat_remain_algorithm(b):
    slope = calculate_slope(0,b[0],2,b[2])
    if slope <= -1.5 and b[1]<=b[0] and b[1]>=b[2]:
        return "leave bed"
    else:
        return "still on bed"
        
        
#     d1 = b[0] - b[1]
#     d2 = b[1] - b[2]
#     d3 = b[0] - b[2]
#     if d1 == 0 and d2 > 2:
#         return "leave bed"
#     elif d1 > 2 and d2 == 0:
#         return "leave bed"
#     elif d1 > 0 and d2 > 0 and d3 > 2:
#         return "leave bed"
#     else:
#         return "still on bed"

In [11]:
b = [19,17,14]
a = heat_remain_algorithm(b)
print(a)

slope: -5.0
leave bed


In [7]:
def leave_bed_algorithm(l,b):
    
    s1 = [[10,11],[0,10,11],[1,10,11],[11,10,11]]
    s2 = [[10,11,10]]
    s3 = [[10,11,0], [10,1,0], [11, 1, 0], [1,11,0]]
    
    if l in s1:
        ans = "notice"  
            
    elif l in s2:
        
        final = heat_remain_algorithm(b)   
        
        if final == "leave bed":
            ans = "leave bed"
            l = [l[-1]]
            b = [b[-1]]            
        else:
            ans = "still on bed"
            l = [l[-1]]
            b = [b[-1]]
        
    elif l in s3:
        ans = "leave bed"
        l = [l[-1]]
        b = [b[-1]]        
    else:
        ans = "do not care"
        
    return ans,l,b

In [ ]:
def leave_bed_algorithm(l,b):
    
    situation1 = [[10,11,10]]
    situation2 = [[10,11,0], [10,1,0], [11, 1, 0], [1,11,0]]
    
    if l in situation1:
        
        final = heat_remain_algorithm(b)   
        
        if final == "leave bed":
            ans = "leave bed"
            l = [l[-1]]
            b = [b[-1]]
            
        else:
            ans = "still on bed"
            l = [l[-1]]
            b = [b[-1]]
            
    elif l in situation2:
        ans = "leave bed"
        l = [l[-1]]
        b = [b[-1]]
        
    else:
        ans = "do not care"
        
    return ans,l,b
    

In [ ]:
def leave_bed_algorithm(l,b):
    
    if l == [10,11,10] or l == [10,1,10]:
        
        final = heat_remain_algorithm(b)
    
        if final == "leave bed":
            ans = "leave bed"
            l = [l[-1]]
            b = [b[-1]]
            return ans, l, b
        else:
            ans = "still on bed"
            l = [l[-1]]
            b = [b[-1]]
            return ans, l, b
            
    elif l == [10,11,0] or l == [10,1,0] or l == [11, 1, 0] or l == [1,11,0]:
        ans = "leave bed"
        l = [l[-1]]
        b = [b[-1]]
        return ans, l, b
    
#     elif l == [0,11,10] or l == [0,1,10] or l == [1,11,10]:
#         ans = "enter bed"
#         l = [l[-1]]
#         b = [b[-1]]
#         return ans, l, b
        
    else:
        ans = "do not care"
        return ans,l,b

## start

In [8]:
model_path = r"C:\Users\ee527\Dementia_Vision_beta\model\test.h5"
model = tf.keras.models.load_model(model_path)

In [9]:
directory_name = r"D:\test_leave_bed\1021"

In [10]:
pre = 99
l = []
b = []
find = []
restrict=3
ans = "initial"
padding = 0
for file_name in os.listdir(directory_name):
    #time1 = time.time() 
    print(file_name) 
    
    image_path = directory_name + "/" + file_name  
    raw = cv2.imread(image_path,0)
    
    bed_dev, floor_dev = get_two_area_stdev(raw)
    bed_dev = int(bed_dev)
    floor_dev = int(floor_dev)
           
        
    # 圖片前處理
    process1 = magic_eraser(raw, threshold=15)
    process1_copy = process1.copy()
    process1[0:16, 0:32] = padding
    process1_copy[16:24, 0:32] = padding 
    
    
    #cv2.imwrite( r"D:\test_leave_bed\1011b" + "/" + file_name, process1_copy) 
    #cv2.imwrite( r"D:\test_error\1011f" + "/" + file_name, process1) 
   
    # 開始預測
    image1 = load(process1_copy)
    image2 = load(process1)
    
    score1, result1 = predict_result(image1,threshold=0.95)
    score2, result2 = predict_result(image2,threshold=0.9)
    
    # 預測結果: 0,1,10,11
    final = result1 * 10 + result2
    #print(final)
    
#     if pre != final:
#         l.append(final)
#     b.append(bed_dev)
    
   
    
    if ans == "notice":
        if pre != final:
            l.append(final)
            b.append(bed_dev)
    else:
        # 狀態變化才紀錄
        if pre != final:
            l.append(final)
        b.append(bed_dev)  
        
    
    list_to_stack(l, restrict)
    list_to_stack(b, restrict)   
    print(l,b)
    
    ans,l,b = leave_bed_algorithm(l,b)       
    print(ans)
    if ans == "leave bed":
        find.append(file_name)
          
    pre = final
    
#     time2 = time.time()
#     print(time2-time1)
    print("")

20211021_t063819.jpg
[10] [13]
do not care

20211021_t063821.jpg
[10] [13, 14]
do not care

20211021_t063823.jpg
[10] [13, 14, 14]
do not care

20211021_t063825.jpg
[10] [14, 14, 13]
do not care

20211021_t063827.jpg
[10] [14, 13, 14]
do not care

20211021_t063829.jpg
[10] [13, 14, 14]
do not care

20211021_t063831.jpg
[10] [14, 14, 14]
do not care

20211021_t063833.jpg
[10] [14, 14, 14]
do not care

20211021_t063835.jpg
[10] [14, 14, 14]
do not care

20211021_t063837.jpg
[10] [14, 14, 14]
do not care

20211021_t063839.jpg
[10] [14, 14, 13]
do not care

20211021_t063841.jpg
[10] [14, 13, 14]
do not care

20211021_t063843.jpg
[10] [13, 14, 13]
do not care

20211021_t063845.jpg
[10] [14, 13, 13]
do not care

20211021_t063847.jpg
[10] [13, 13, 14]
do not care

20211021_t063849.jpg
[10] [13, 14, 13]
do not care

20211021_t063851.jpg
[10] [14, 13, 14]
do not care

20211021_t063853.jpg
[10] [13, 14, 14]
do not care

20211021_t063855.jpg
[10] [14, 14, 15]
do not care

20211021_t063857.jpg
[10

In [15]:
print(find)

['20211015_t000720.jpg', '20211015_t000748.jpg']


## test

In [ ]:
directory_name = r"D:\test_leave_bed\1012"
for file_name in os.listdir(directory_name):
    #time1 = time.time() 
    print(file_name) 
    image_path = directory_name + "/" + file_name  
    raw = cv2.imread(image_path,0)
    (mean , stddv) = cv2.meanStdDev(raw)
    print(mean,stddv)
    print("")

In [4]:
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from sklearn.metrics.pairwise import cosine_similarity
from PIL import Image
import numpy as np
from skimage import transform
import os
import shutil
import tensorflow as tf
from tensorflow import keras
import cv2
import time

def load(image):
      
    np_image = np.array(image).astype('float32')/255
    np_image = transform.resize(np_image, (128,128,3))
    np_image = np.expand_dims(np_image, axis=0)
    return np_image

model_path = r"C:\Users\ee527\Dementia_Vision_beta\model\test.h5"
model = tf.keras.models.load_model(model_path)
# see all layer
for idx in range(len(model.layers)):
    print(model.get_layer(index = idx).name)

input_1
block1_conv1
block1_conv2
block1_pool
block2_conv1
block2_conv2
block2_pool
block3_conv1
block3_conv2
block3_conv3
block3_conv4
block3_pool
block4_conv1
block4_conv2
block4_conv3
block4_conv4
block4_pool
block5_conv1
block5_conv2
block5_conv3
block5_conv4
block5_pool
global_max_pooling2d
dropout
batch_normalization
dropout_1
dense


In [49]:
layer_model = tf.keras.models.Model(inputs=model.input,outputs=model.get_layer('block5_pool').output)

In [65]:
raw = cv2.imread(r"D:\test_leave_bed\1007\20211007_t031941.jpg",0)
x_test = load(raw)
raw2 = cv2.imread(r"D:\test_leave_bed\1007\20211007_t031943.jpg",0)
x_test2 = load(raw2)

output = layer_model.predict(x_test)
output2 = layer_model.predict(x_test2)

features_compress = output.flatten()
features_compress2 = output2.flatten()
print(features_compress)
print(features_compress2)
print('cosine_similarity:', cosine_similarity([features_compress], [features_compress2]))

[0.09809732 0.         0.         ... 0.         0.74140555 0.        ]
[0.13304383 0.         0.         ... 0.         0.44589236 0.        ]
cosine_similarity: [[0.98333925]]
